### ISSUE TITLE
generate vector.bin

### ISSUE THREAD

**Issue by onrkrsy** [tmteam/Word2vec.Tools#5]
can we generate vectors.bin or txt with this tools ?

**Comment by tmteam** [comment]
No. It's madness to do that on C#. Use the google tools instead:https://code.google.com/archive/p/word2vec/ 


  
  




-- С уважением, tt+79032336811

**Comment by omrishsu** [comment]
There is an updated tool to generate the vectors.bin file?

**Comment by tmteam** [comment]
> There is an updated tool to generate the vectors.bin file?

No, "Word2Vec.Tools" is a tool for work  with already existed vectors.bin

To generate Vectors.bin you should use official google toolkit: https://code.google.com/archive/p/word2vec/
